apiVersion: v1
kind: Service
metadata:
  name: balancer
spec:
  selector:
    app: nginx
  type: LoadBalancer
  externalIPs:
    - <BALANCER IP>
  ports:
    - name: http
      port: 80
      targetPort: 30001