apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf  # Mount the NGINX configuration file
              subPath: nginx.conf  # Subpath inside the volume
            - name: nginx-index
              mountPath: /usr/share/nginx/html/
            - name: cert
              mountPath: '/etc/nginx/cert.pem'
              subPath: 'cert.pem'
            - name: cert-key
              mountPath: '/etc/nginx/cert-key.pem'
              subPath: 'cert-key.pem'
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config  # Name of the ConfigMap
        - name: nginx-index
          configMap:
            name: index
        - name: cert
          secret:
            secretName: cert
        - name: cert-key
          secret:
            secretName: cert-key