apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  labels:
    app: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: requarks/wiki:latest
          ports:
            - containerPort: 3000
              name: http2 # <- pain
          env:
            - name: DB_TYPE
              value: 'postgres'
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: 'wiki'
            - name: DB_PASS
              value: 'Passw0rd'
            - name: DB_NAME
              value: 'wiki_db'