apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  labels:
    app: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: lscr.io/linuxserver/wikijs:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Etc/UTC
      volumes:
        - name: config
          hostPath:
            path: /wikijs/config
        - name: data
          hostPath:
            path: /wikijs/data
