---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secret-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ots
  labels:
    app: ots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ots
  template:
    metadata:
      labels:
        app: ots
    spec:
      containers:
        - name: ots
          image: dismantl/onetimesecret
          ports:
            - containerPort: 7143
          volumeMounts:
            - name: data
              mountPath: "/data"
              
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: secret-pvc

