apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca
  labels:
    app: ejbca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ejbca
  template:
    metadata:
      labels:
        app: ejbca
    spec:
      containers:
        - name: ejbca
          image: keyfactor/ejbca-ce
          resources:
            requests:
              memory: 512Mi
              cpu: "250m"
            limits:
              memory: 1024Mi
              cpu: "500m"
          ports:
            - containerPort: 8443
          env:
            - name: TLS_SETUP_ENABLED
              value: simple
            - name: DATABASE_JDBC_URL
              value: "jdbc:postgresql://postgres-service:5432/ejbca_db?characterEncoding=utf8"
            - name: DATABASE_USER
              value: ejbca_usr
            - name: DATABASE_PASSWORD
              value: Passw0rd