apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'bitnami/postgresql'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 512Mi
              cpu: "250m"
            limits:
              memory: 1024Mi
              cpu: "500m"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgresdata
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb
          env:
            - name: POSTGRESQL_USERNAME
              value: "enta"
            - name: POSTGRESQL_PASSWORD
              value: "Passw0rd"
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: initdb
          configMap:
            name: postgres-initdb