apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'bitnami/postgresql'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 512Mi
              cpu: "250m"
            limits:
              memory: 1024Mi
              cpu: "500m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgresdata
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb-01
          env:
            - name: POSTGRESQL_USERNAME
              value: "postgres"
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: default_pass
                  name: cluster-secrets
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: initdb-01
          configMap:
            name: postgres-initdb