apiVersion: v1
kind: Service
metadata:
  name: balancer
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 30001
    - name: https
      port: 443
      targetPort: 30002
