apiVersion: v1
kind: Service
metadata:
  name: balancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 30001
    - name: https
      port: 443
      targetPort: 30002