apiVersion: v1
kind: Service
metadata:
  name: balancer
spec:
  selector:
    app: nginx-proxy
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: postgres
      port: 5432
      targetPort: 5432
