apiVersion: v1
kind: Service
metadata:
  name: balancer
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 30001
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 30002
      nodePort: 30443
