apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  labels:
    app: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: requarks/wiki:latest
          resources:
            requests:
              memory: 512Mi
              cpu: "250m"
            limits:
              memory: 1024Mi
              cpu: "500m"
          ports:
            - containerPort: 3000
              name: http1 # <- pain
          env:
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: wiki_usr
                  name: cluster-secrets
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: wiki_pass
                  name: cluster-secrets
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: wiki_db
                  name: cluster-secrets